### PR TITLE
Auto-comment #3

### PR DESCRIPTION
**Pull request by hana-maria**
Issue #3 
Added a .yml file for auto-comments on issues opened and closed. I tested it locally (through act) and it successfully ran but the preview.yml which already exists in the repo is giving some issue @vansh-codes 

Screenshot 2024-10-08 at 11 56 56 AM

### CODE REVIEW

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Remove changes from preview.yml file

**Comment by hana-maria** [comment]
@vansh-codes i haven't added any changes to the file, i tried commenting the whole thing just to check if it still fails in the actions tab and reverted it back to the original

**Comment by vansh-codes** [comment]
It shows few changes in that file, please revert it back or copy paste from the original file

**Comment by hana-maria** [comment]
@vansh-codes done

**Review by vansh-codes — APPROVED** [review]
Done

**Review by vansh-codes — APPROVED** [review]

**Pull request merged**
