### PR TITLE
added a moving gradient bg

### PR DESCRIPTION
**Pull request by bhaviya18**
Added a gradient bag that will increase the chaos.

image

### CODE REVIEW

**Comment by vansh-codes** [comment]
Can you sharea a video proof of this?

**Comment by bhaviya18** [comment]
I added more background colors to the webpage. I tried screen recording it. 

https://github.com/user-attachments/assets/5fe0af7b-7b78-481f-8a22-5e96e9e0ec2c

**Comment by bhaviya18** [comment]
If you want I can add more colors or make the gradient move faster.

**Comment by vansh-codes** [comment]
Resolve merge conflicts so that I can merge it

**Comment by bhaviya18** [comment]
Im sorry I couldnt understand the conflicts. Also I cant find the search bar. Can you please guide me.

**Comment by vansh-codes** [comment]
I resolved the conflicts @bhaviya18

**Comment by bhaviya18** [comment]
Thank you!

**Pull request merged**
