### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by shrashti-19**
Closes: #82 
Introduce intentional delays in buttons, sliders and other interactive elements. For example, buttons only respond after a 5-second lag, or sliders move at an unpredictable slow speed. This feature amplify user frustration and confusion, enhancing the chaotic experience of ChaosWeb. 

Please review the work @vansh-codes

### CODE REVIEW

**Comment by vansh-codes** [comment]
Which issue did you work upon, please mention the issue number and resolve the conflicts

**Comment by shrashti-19** [comment]
> Which issue did you work upon, please mention the issue number and resolve the conflicts

 Chaotic Feat: Laggy Interactions for increased Chaos (Issue #82)

**Comment by vansh-codes** [comment]
Resolve merge conflicts

**Comment by vansh-codes** [comment]
Will you resolve the merge conflicts? @shrashti-19

**Pull request closed without merging**
