### PR TITLE
ISSUE #4: Creation of ChaosWeb logo

### PR DESCRIPTION
**Pull request by kanduru-abhiram**
Closes: #4

I have created the ChaosWeb logo using Inkscape Software.

I kept these below points in mind while designing the logo:

The logo should be confusing to read - So added the vertical flip name of ChaosWeb
The design shouldn't be symmetrical - So, the font size of top and bottom are different and the line in between is not symmetric
Weird design - The logo will itself explain it
Not about smooth navigation or polished interfaces - The font of the logo doesn't have rounded corners
I can redesign the logo if we are introducing light mode and dark mode.

I have created an assets folder and kept the logo in that folder and created .svg, .png and .ico formats of the logo as well.
I hope the logo is in high quality. That's the reason of adding multiple types and not just limiting with above 3 formats.

If accepted, please accept this PR under Hacktoberfest2024 and please do add hacktoberfest,hacktoberfest-accepted and hactoberfest2024 labels.

### CODE REVIEW

**Comment by vansh-codes** [comment]
Mention your issue as 
Closes: #issuenumber

**Review by vansh-codes — CHANGES_REQUESTED** [review]
This will be the favicon of the website so this image aspect wont work
Changes:
- search for image aspect of favicon of websites, according modify .ico file liek this to be in circular👇 
image

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Remove the mirror images from all of this as only the original one on the top looks good so remove the below mirror image
image

**Comment by vansh-codes** [comment]
Are you working on the changes @kanduru-abhiram ??

**Comment by kanduru-abhiram** [comment]
Yes, I'm working on the changes bro @vansh-codes

**Comment by vansh-codes** [comment]
@kanduru-abhiram 
1. Remove the black grey line as well from the bottom
2. remove the grey sentence which I marked red in the photo shared before
3. every file should have it in circular aspect like the example I shared and make sure they are high quality images
4. remove the .pdf file as it is not needed at all

**Comment by kanduru-abhiram** [comment]
Hey @vansh-codes ,

Will this one works?

image

Please confirm all the changes and sort it out, so, I'll finally, create a final pull request.

**Comment by vansh-codes** [comment]
Add ` 😵‍💫 ` this emoji in between the circle in png image and thats it

**Comment by kanduru-abhiram** [comment]
Sure @vansh-codes,
I hope this one will work right?

image

I'll add this emoji and create a new pull request, thanks for the support.

**Pull request closed without merging**
