### PR TITLE
Added Simon game[new feature]

### PR DESCRIPTION
**Pull request by Bhumika-00**
Closes: #130

Simon is a memory-based game that challenges players to remember and reproduce a sequence of colors (or sounds) that the game generates.

### CODE REVIEW

**Comment by Bhumika-00** [comment]
Screenshot from 2024-10-15 16-30-45
Screenshot from 2024-10-15 16-30-55
I have added a new game plaese review this
Screenshot from 2024-10-15 16-30-38
Screenshot from 2024-10-15 16-30-42

**Comment by Bhumika-00** [comment]
Added a new game please review it

**Comment by vansh-codes** [comment]
Share a video, I am not able to understand from screenshots, also mention the issue number which was assigned to you and on which you worked

**Comment by Bhumika-00** [comment]
The issue wasn't raised.... I just made a new chaotic game add make a pr I
am sending you the video

**Comment by vansh-codes** [comment]
Issue should be raised first and then it will be assigned to you and then you can contribute and create PR

**Comment by Bhumika-00** [comment]
I have raised the issue

**Comment by vansh-codes** [comment]
Share video with sound

**Comment by vansh-codes** [comment]
no let it be, but share a video for me to see and review

**Comment by Bhumika-00** [comment]
Okay fine

**Comment by Bhumika-00** [comment]
Btw I am adding some new chaos too by the time you can review it

**Review by vansh-codes — APPROVED** [review]

**Comment by Bhumika-00** [comment]
Thanks

**Pull request merged**
