### PR TITLE
Maze Game and Inverted color

### PR DESCRIPTION
**Pull request by bhaviya18**
I have added the maze game using react. I hope you will like it. 
Closes: #111 
Closes: #112 
https://github.com/user-attachments/assets/6db02edd-f899-4a3e-9441-4d48bbdf1c47

### CODE REVIEW

**Comment by bhaviya18** [comment]
I raised 2 issues, but it is not taking them separately, I dont know how to manage that. But can you please assign me points accordingly, as I resolved 2 issues.

**Comment by vansh-codes** [comment]
1. which two issues did you work upon?
2. I dont find anything chaotic in the recording you shared, can you rework on it and make it chaotic in functionality along with UI
3. Resolve merge conflicts
4. After all these 3 tasks, commit and tag me

**Comment by bhaviya18** [comment]
1st issue was maze game and 2nd one was inverted color toggle butto

**Comment by vansh-codes** [comment]
resolve conflicts

**Comment by bhaviya18** [comment]
I cannot understand the conflicts. Can you guide me please.

**Comment by vansh-codes** [comment]
The place where you added code, there already exists some code thats why it has merge conflicts, if you have added some new lines then shift the position of those lines which are creating conflicts, try understanding if not then search on google or youtube once, it would help you understand better

**Comment by bhaviya18** [comment]
Please review @vansh-codes , it shows checks have failed.

**Comment by bhaviya18** [comment]
Please review my PR.

**Comment by vansh-codes** [comment]
Share screenshots and videos of your work

**Comment by bhaviya18** [comment]
here is the video.

Uploading maze game and invert button.mp4…

**Comment by bhaviya18** [comment]
@vansh-codes I have mailed you the video of my work.

**Comment by bhaviya18** [comment]
here is the video of my work
https://github.com/user-attachments/assets/75e55873-085b-4a2b-a3a2-6cfe74e3f96f

**Review by vansh-codes — APPROVED** [review]

**Comment by vansh-codes** [comment]
image

Fix this errors

**Comment by vansh-codes** [comment]
Fix the conflicts

**Comment by bhaviya18** [comment]
@vansh-codes  Review please.

**Review by vansh-codes — APPROVED** [review]

**Comment by bhaviya18** [comment]
Thank you soo much

**Pull request merged**
