### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eshalshaikh07**
Closes: #93 
Hey!!
added animations hope you like it

### CODE REVIEW

**Comment by vansh-codes** [comment]
Please share the video of the new readme you created

**Comment by eshalshaikh07** [comment]
> Please share the video of the new readme you created  
https://github.com/eshalshaikh07/ChaosWeb/blob/main/README.md check this!

**Comment by eshalshaikh07** [comment]
dropped the link please check!

**Comment by vansh-codes** [comment]
Remove the red animated lines, its too distracting and doesnt looks good! Remove them and commit so I can merge

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Do the asked changes
- remove red animation lines

**Comment by eshalshaikh07** [comment]
https://github.com/eshalshaikh07/ChaosWeb/blob/main/README.md removed red lines!!!

**Review by vansh-codes — APPROVED** [review]
Lgtm 💥

**Comment by vansh-codes** [comment]
Share your issue link asap

**Pull request merged**
