### PR TITLE
ISSUE #4: Creation and Updation of ChaosWeb logo

### PR DESCRIPTION
**Pull request by kanduru-abhiram**
Hey @vansh-codes,

Closes: #16 and #4

I have created the ChaosWeb logo using Inkscape Software.

As discussed in PR: #16 
I have done the requested changes and created the final pull request.

I have created an assets folder and kept the logo in that folder and created .svg, .png and .ico formats of the logo as well.
I hope the logo is in high quality. That's the reason of adding multiple types and not just limiting with above 3 formats.

If accepted, please accept this PR under Hacktoberfest2024 and please do add hacktoberfest,hacktoberfest-accepted and hactoberfest2024 labels.

### CODE REVIEW

**Review by vansh-codes — APPROVED** [review]
Looks good

**Comment by kanduru-abhiram** [comment]
Hey @vansh-codes,

Thanks for accepting my PR.
I am also an GSSoc 2024 Contributor, please add gssoc,gssoc2024 and gssoc-ext tags.

Lets connect for some good collaborations.
https://linkedin.com/in/k-abhiram

**Comment by vansh-codes** [comment]
image

You should've marked it here if you are gssoc contributor as well!
take care of this from next time!

**Comment by kanduru-abhiram** [comment]
Actually, I got confirmation from GSSoc yesterday night, but I'll defintely remember this from next time, thanks bro

**Pull request merged**
