### PR TITLE
made signup page move and chaotic and made connect four game impossib…

### PR DESCRIPTION
**Pull request by deeksha1010**
### Pull Request Description

**Title:** Chaotic Updates to Signup Page and Connect Four Game

**Overview:**
This PR introduces chaotic changes to the signup page and the Connect Four game, making them visually confusing and unplayable.

**Changes Made:**
1. **Signup Page:** Layout altered for chaos, with random animations hindering navigation.
2. **Connect Four Game:** Key functionalities modified, rendering the game unplayable.

please add gssoc-ext tag which will help me participate

### CODE REVIEW

**Comment by vansh-codes** [comment]
Which issue did you work upon, please mention the issue number

**Comment by deeksha1010** [comment]
issue #199

**Comment by vansh-codes** [comment]
@deeksha1010 you have to first create issue and wait till its assigned

**Comment by vansh-codes** [comment]
Connect four game already exists #159
I dont think your issue and PR is relevant at this time and also you didnt wait for issue to be assigned, I am closing your issue as well as PR

**Comment by deeksha1010** [comment]
i had made connectfour more chaotic, anyways thanks for your consideration.

**Pull request closed without merging**
