### PR TITLE
Added chaos movement in the About us page!!

### PR DESCRIPTION
**Pull request by Jay-1409**
https://github.com/user-attachments/assets/746a3b7a-9dd3-4081-8141-672930f1c926

#103 
@vansh-codes

### CODE REVIEW

**Review by vansh-codes — CHANGES_REQUESTED** [review]
It should dynamically add new contributors, I think you have hardcoded the contributors for now, please make it dynamic

**Comment by Jay-1409** [comment]
> It should dynamically add new contributors, I think you have hardcoded the contributors for now, please make it dynamic

oh ok i will do that then.

**Review by vansh-codes — APPROVED** [review]
Lgtm!

**Comment by Jay-1409** [comment]
can i get a level 2 please ?

**Pull request merged**
