### PR TITLE
Implement GitHub PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
**FIX** #149 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`FIX #<issue-number>` or `FEAT, or DOC #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@vansh-codes

### CODE REVIEW

**Comment by vansh-codes** [comment]
You wrote `FIX` but it should be `Closes` or `Fixes`
Please update it in your PR description

**Comment by vansh-codes** [comment]
`GITHUB_EVENT_PULL_REQUEST_BODY`
`GITHUB_EVENT_PULL_REQUEST_TITLE`

What are these 2 env?
Do I have to store them or its already provided by GitHub ?

**Comment by smog-root** [comment]
> `GITHUB_EVENT_PULL_REQUEST_BODY` `GITHUB_EVENT_PULL_REQUEST_TITLE`
> 
> What are these 2 env? Do I have to store them or its already provided by GitHub ?

No. you don't store it!!

**Comment by smog-root** [comment]
can you make it level2 please??!!

**Comment by smog-root** [comment]
> You wrote `FIX` but it should be `Closes` or `Fixes` Please update it in your PR description

changes done! @vansh-codes

**Comment by vansh-codes** [comment]
DUPLICATE from #145

**Pull request closed without merging**
