### PR TITLE
Remove horizontal scroll

### LINKED ISSUE #140: CHAOS REPORT: Horizontal scroll bar is not good
### Is there an actual issue here?

- [X] I have verified this isn't part of ChaosWeb's intentional disorder

### Describe the unexpected!

The horizontal scroll bar is not looking good and also is bit unstandard. I would like to remove it and maintain the screen's height width

Screenshot 2024-10-18 172330

### Confirm

- [X] I understand ChaosWeb is intentionally designed to be messy
- [X] I agree to follow this project's Code of Conduct
- [X] I found a genuine bug amidst the chaos
- [X] I'm enjoying the mess!
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #140 

This PR removes the horizontal scroll bar form the home page.

Screenshot 2024-10-20 205202

### CODE REVIEW

**Comment by vansh-codes** [comment]
We need horizontal scroll buddy! The website is supposed to have horizontal scroll
Read the `README.md`

**Comment by haseebzaki-07** [comment]
I was assigned so I removed it @vansh-codes
issue #154

**Comment by vansh-codes** [comment]
Sorry I misunderstood as you want to redesign the scrollbar 
Can you please share the video proof of how it looks now after removing the horizontal scrollbar

**Comment by haseebzaki-07** [comment]
https://github.com/user-attachments/assets/f781b580-b8b4-4d3e-94f8-c5cd3d24b8ec

Hey @vansh-codes here it is!

**Comment by vansh-codes** [comment]
ok works! 👍

**Review by vansh-codes — APPROVED** [review]

**Pull request merged**
