### PR TITLE
Add Dynamic Jump Scare Feature with Full Spookiness and Chaos

### LINKED ISSUE #105: Chaotic Feat: Proposal to Add Horror-Themed Features (Jump Scares & Creepy Cursor)
### Describe your chaotic idea

Hi,

I hope you're doing well! I’d like to propose adding two exciting, horror-themed features to the ChaosWeb project that align with its chaotic and unconventional nature.

1. **Jump Scares:**
I plan to introduce random jump scares triggered when hovering over specific elements like buttons, sliders, images. These will be spooky images that appear briefly on the screen, adding to the chaotic and eerie atmosphere.

2. **Creepy Cursor:**
This feature will change the default cursor to a creepy hand (or other eerie icon) to enhance the overall unsettling experience while navigating the site.

**Merge Conflict Assurance:**
To ensure a smooth integration, I will work on these features in a separate branch, making sure the changes are isolated to new assets (images) and minor, non-disruptive additions to existing JavaScript and CSS files. This will prevent any merge conflicts with ongoing or future work on the main branch.

Please let me know your thoughts! I’m excited to contribute and make the project even more delightfully chaotic. 😈

Please add all labels which rely under hacktoberfest and gssoc-ext 2024 with level 3.
please...

### Add Screenshots or Sketches

Not now, when i am done i'll share you screenrecord

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

### PR DESCRIPTION
**Pull request by sumitkumar9128**
fixes #105 

**Description:** This PR introduces a new, dynamic jump scare feature, designed to enhance the horror theme with intense spookiness and chaos. The jump scare effect includes:

Randomized creepy images that pop up on-screen to surprise users.
Flickering animations and randomized positioning to intensify the horror effect.
Custom CSS and isolated component structure, ensuring no merge conflicts now or in the future.

**Additional Context:**

For a demonstration of the effect, refer to the attached video.
The creepy cursor effect was not included due to browser compatibility issues and potential caching problems that affected consistent rendering.

https://github.com/user-attachments/assets/817c64a1-91be-4246-939e-13d844a78507

 If you’d like to change any of the jump scare images, simply:

Add or replace image files in the src/assets/creepyImg directory.
Update the array of images in JumpScareEffect.jsx to include the new images. (just need to update img name)
The feature has been fully tested for merge compatibility and isolated from other components, with only minimal modifications in App.jsx. Feel free to merge anytime!

### CODE REVIEW

**Comment by vansh-codes** [comment]
Share screenshot and video

**Comment by sumitkumar9128** [comment]
hey @vansh-codes  check the video, 
The jump scare effect is triggered unpredictably by user interactions, including hovering over elements, clicking, and scrolling. This adds an element of surprise that aligns with the website's chaotic theme.

**Comment by vansh-codes** [comment]
Looks scary! 👻

**Review by vansh-codes — APPROVED** [review]
Chaotic!

**Pull request merged**
