### PR TITLE
hactoberfest image change in readme.md

### PR DESCRIPTION
**Pull request by likitha-kapu**
Closes: #220 
changed the image of hactoberfest in readme.md

### CODE REVIEW

**Comment by likitha-kapu** [comment]
@vansh-codes please check out my pull request

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Please add an url instead of adding image to the repo

**Comment by likitha-kapu** [comment]
@vansh-codes check out once

**Review by vansh-codes — CHANGES_REQUESTED** [review]
You can just drop the image there, github will automatically generate a url, just drag and drop there

**Comment by likitha-kapu** [comment]
Screenshot 2024-11-03 161210

**Comment by likitha-kapu** [comment]
@vansh-codes please check out my pull request once

**Review by vansh-codes — APPROVED** [review]
Good job!

**Pull request merged**
