### PR TITLE
change in css in id chaos-header-span

### PR DESCRIPTION
**Pull request by Bhumibathre**
I adjusted the color of the chaos-header-span ID in CSS to resolve an issue where the previous color was blending with the background, ensuring better readability and contrast.

### CODE REVIEW

**Comment by Bhumibathre** [comment]
> Which issue number did you work upon? I cant see any issues related to this!

In color !

**Comment by vansh-codes** [comment]
You have to create an issue first from [create issue here](https://github.com/vansh-codes/ChaosWeb/issues) and wait for it to be assigned and then create a PR, you can directly raise a PR.
If you created an issue, share the link here

**Comment by Bhumibathre** [comment]
> You have to create an issue first from [create issue here](https://github.com/vansh-codes/ChaosWeb/issues) and wait for it to be assigned and then create a PR, you can directly raise a PR.
> If you created an issue, share the link here

Ok sir

**Comment by vansh-codes** [comment]
I am closing this PR
From next time, raise an issue first, wait till its assigned to you then start working and create PR
Read the contributing guidelines for all repos wherever you contribute

**Pull request closed without merging**
