### PR TITLE
Automated of project structure updation using GitHub workflows and Python scripts

### LINKED ISSUE #193: Chaotic Feat: Automation of project structure updation using GitHub workflows and Python scripts
### Describe your chaotic idea

Currently, the project doesn't have a project structure. And, it would be a bit difficult for newcomers to understand the project and how to add more chaos to it's existing structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and Python script will make the maintenance easier and enhance organised chaos(metaphor!).

I want to add a detailed project structure in a separate file(redirect in README.md) for the contributors to refer to and automate its updation process as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand the structure and spread more chaos to the project. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and a Python script will make the project more accessible to the Contributors and spread more chaos.

### Add Screenshots or Sketches

Sample of how the workflow would be automated and the project structure after updation in readme:
image

image

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved:

- Closes #193 

# Description

I have added the Project Repository in a new file named **PROJECT_STRUCTURE.md** :
image
image
image
image

I have automated the updation of the Project Structure using GitHub workflows and Python scripts. The Project Structure will update when you push any changes to the **main** branch

I have also added a redirect to the file in the README.md file:
image

### CODE REVIEW

**Comment by vansh-codes** [comment]
```
gh_token = os.getenv('GH_TOKEN')
gh_repo = os.getenv('GITHUB_REPOSITORY')
````

Do I have to create any personal access tokens?
I can see it in your code

also whats the difference between repo_structure and project_structure

**Comment by rajdeepchakraborty-rc** [comment]
> ```
> gh_token = os.getenv('GH_TOKEN')
> gh_repo = os.getenv('GITHUB_REPOSITORY')
> ```
> 
> Do I have to create any personal access tokens? I can see it in your code
> 
> also whats the difference between repo_structure and project_structure

You don't have to make any personalized tokens. 
Also repo_structure is a text file where I have used python file handling to create the repository structure first and then the project_structure.md file is to add the headings and other stuff(HTML markdown structure) to make it look good and accessible.

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes Check the commit history, I have already tested it once and I have not changed any tokens. It will work as long as the Github Actions bot has write permissions which I have provided:
```
permissions:
      contents: write   # Permission to the GitHub Bot to access and update the Project Repository
```
This was creating an issue previously and I debugged it.

**Comment by vansh-codes** [comment]
why is repo_structure is needed?

**Comment by rajdeepchakraborty-rc** [comment]
> why is repo_structure is needed?

repo_structure is a **.txt(text)** file and the python code was not working earlier on the **.md(Markdown)** file.

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes Have I answered your query?

**Comment by vansh-codes** [comment]
Okay got it @rajdeepchakraborty-rc

**Review by vansh-codes — APPROVED** [review]
Good job! Keep up the good work

**Comment by vansh-codes** [comment]
Rewarded level3 for your good work, documentation and such things has to be level2 but you did a goodjob thats why i am giving you level3 on this

**Comment by vansh-codes** [comment]
[Gityzer](https://github.com/vansh-codes/gityzer) 

Please create same issue for this project also

**Comment by rajdeepchakraborty-rc** [comment]
> [Gityzer](https://github.com/vansh-codes/gityzer)
> 
> Please create same issue for this project also

@vansh-codes I will do it by tomorrow and let you know. It is late night for me today and I am signing off for today.

**Comment by rajdeepchakraborty-rc** [comment]
> Rewarded level3 for your good work, documentation and such things has to be level2 but you did a goodjob thats why i am giving you level3 on this

Thanks for the appreciation. I am glad that this feature is helpful to people.

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes I have opened the issue at:
https://github.com/vansh-codes/Gityzer/issues/71
You can assign it to me. I will complete the work by tomorrow.

**Pull request merged**
