### PR TITLE
I have added the emojis as discussed

### PR DESCRIPTION
**Pull request by anshdeep0504**
Screenshot from 2024-10-31 01-17-05
@vansh-codes please close the PR.
problem #205

### CODE REVIEW

**Review by vansh-codes — APPROVED** [review]

**Comment by vansh-codes** [comment]
Resolve the conflicts @anshdeep0504

**Comment by anshdeep0504** [comment]
@vansh-codes  It is showing the branch has no conflicts.

**Comment by vansh-codes** [comment]
Share the screenshots of how it looks now

**Comment by vansh-codes** [comment]
Share screenshot @anshdeep0504

**Pull request closed without merging**
