### PR TITLE
Feature random navigate, Auto-Redirect to random pages

### PR DESCRIPTION
**Pull request by hamzathul**
This pull request introduces a new chaotic feature that randomly redirects users to different pages in the app for every 30 seconds time interval, enhancing the chaotic experience of the website. 

Closes: #118

### CODE REVIEW

**Comment by vansh-codes** [comment]
Share a working video of your work

**Comment by vansh-codes** [comment]
one modification I want:
- change the time from 30seconds to random time
- it should everytime redirect in random seconds from 10 to 30
- Do this changes and let me know

**Comment by hamzathul** [comment]
added 10 to 30 seconds randomTime.

video attached below:
[Video](https://github.com/user-attachments/assets/f036a45e-9201-475b-bcd5-35361a0eb159)

**Review by vansh-codes — APPROVED** [review]
Looks good!

**Pull request merged**
