### PR TITLE
Feat:Implement DVD Logo Dancer Feature

### PR DESCRIPTION
**Pull request by RachitSahu26**
This pull request addresses issue #109, "Chaotic Feat: Bouncing Div Like DVD Logo Effect."

Functionality: I have successfully implemented the DVD logo effect, which includes a bouncing animation that mimics the classic DVD logo movement. The logo smoothly transitions across the screen, bouncing off the edges, providing a dynamic visual effect.

Bug Fixes: During development, I identified and resolved issues related to the SVG tag usage, ensuring proper rendering and responsiveness of the logo component.

Testing: I have thoroughly reviewed the changes, and everything is functioning as expected. The animation performs smoothly without any lag or visual glitches.

fixed:#109

https://github.com/user-attachments/assets/c908e9cf-93fc-4342-b319-f5308f7bb457

### CODE REVIEW

**Comment by RachitSahu26** [comment]
I fixed the issue of duplicate SVGs and removed redundant imports of the popup and logo components, streamlining the code. Everything is now functioning smoothly.

**Comment by vansh-codes** [comment]
issue #109 was assigned to someone else @RachitSahu26 
You have to work only on those issues assigned to you, the person assigned replied that he is working on it so cant accept this PR
I am closing this PR as invalid
Please take care and read the guidelines from next time

**Comment by RachitSahu26** [comment]
@vansh-codes The person assigned to this issue has been working on it for over a week without resolving it. I noticed this and thought I could help, so I resolved it within 2 hours and submitted a PR. Please don’t close it, as I’ve put in time and effort to contribute.

Thanks!

**Comment by vansh-codes** [comment]
I agree to your point, but we dont know the other persons story, he might be having exams or might be busy with something else, you commented there and the person replied that he is working on it, if he wouldnt have replied and confirmed then I might have give it to you and merge your PR, I agree and acknowledge your efforts for this PR but few rules and ethics has to be followed, sorry for this time!

**Pull request closed without merging**
