### PR TITLE
5 webpages were made Responsive 

### PR DESCRIPTION
**Pull request by srivishnu2805**
Closes: #113 
I have made almost 5 web pages responsive but the home page and Timeline page have some animation and hover effects so they prevent the responsiveness of the home and timeline pages  Other than that all other pages were made responsive and proper alignment was given to the contents so it looks best than before.

### CODE REVIEW

**Comment by vansh-codes** [comment]
Share screenshots and videos of all page changes done

**Comment by srivishnu2805** [comment]
@vansh-codes These are the images that made some alterations and responsive on all devices

image
image
image
image
image
image
image
image
image
image

**Comment by srivishnu2805** [comment]
@vansh-codes please verify the code and screenshots given and merge it

**Review by vansh-codes — APPROVED** [review]
Goodjob!

**Pull request merged**
