### PR TITLE
Chaos Game

### PR DESCRIPTION
**Pull request by samriddhitiwary**
Closes: #186 
Dive into the challenging world of LightsOut, where strategy meets puzzle-solving! Your objective is to turn off all the lights on the grid by clicking on them. Each click toggles the selected light and its adjacent neighbors. Can you find the winning strategy to extinguish all the lights? Perfect for players of all ages, this engaging game sharpens your critical thinking and problem-solving skills while providing hours of fun. Are you ready to conquer the grid?

Issue number: #186 

https://github.com/user-attachments/assets/02506dc1-142e-44fa-949a-1e47c191e829

### CODE REVIEW

**Comment by vansh-codes** [comment]
Please menion your issue on which you worked

**Comment by samriddhitiwary** [comment]
@vansh-codes 
Issue number: https://github.com/vansh-codes/ChaosWeb/issues/186

**Comment by samriddhitiwary** [comment]
Thank you for merging! Just to confirm, wasn't that a level-2 PR issue?
Level1 is for bugs right?

**Comment by vansh-codes** [comment]
It doesnt seem to be level2, also its 200 line changes so thats why level1 is good for it

**Pull request merged**
