### PR TITLE
Purohitk007😎

### PR DESCRIPTION
**Pull request by Kpurohit007**
adding more features in night & testing .html pages with divine functionality of JavaScript..

### CODE REVIEW

**Comment by vansh-codes** [comment]
Please mention the issue which you worked upon `Closes: #issueNumber`
Also please share a working video for what changes have you did and how it looks

**Comment by Kpurohit007** [comment]
Yep

**Comment by Kpurohit007** [comment]
i have added some context feature in night view of the system , adding some query in javascript.

**Comment by vansh-codes** [comment]
Mention the issue you worked upon in the PR description asap

**Pull request closed without merging**
