### PR TITLE
feat: Chaos in Contact form input fields

### LINKED ISSUE #14: Chaotic Feat: Add animations to input text in Contact page
### Describe your chaotic idea

I would like to add dangling/chaotic animation animation to the input text of contact form.

### Add Screenshots or Sketches

N/A

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

### PR DESCRIPTION
**Pull request by KhawajaFashi**
This pr intends to cause chaos in the input field of contact forms.
fixes #14

https://github.com/user-attachments/assets/fefe6d2a-a725-45ac-af33-b52460cd98f7

Labels: 
- Priority: Medium
- Level: 1
- gssoc-extd

### CODE REVIEW

**Comment by KhawajaFashi** [comment]
Sir, I am having a failure with the deployment. Can you guide on this.

**Comment by vansh-codes** [comment]
@KhawajaFashi  Firstly tell me which issue did you work upon
Mention on your issue like this ⬇️ 
`Closes: #issuenumber`

**Comment by KhawajaFashi** [comment]
> @KhawajaFashi  Firstly tell me which issue did you work upon
> Mention on your issue like this ⬇️ 
> `Closes: #issuenumber`

Closes: #14

**Comment by KhawajaFashi** [comment]
> @KhawajaFashi  Firstly tell me which issue did you work upon
> Mention on your issue like this ⬇️ 
> `Closes: #issuenumber`

Closes: #14

**Comment by vansh-codes** [comment]
image

These are the errors due to which deployment is failed, please look into it

**Comment by KhawajaFashi** [comment]
I have fixed the errors in navbar.jsx then what could be the problem now?

**Comment by vansh-codes** [comment]
Close this PR and create a new one
Mention the issue as well as this PR in the new PR

**Pull request closed without merging**
