### PR TITLE
Chaotic Feat: Add Parallax Scrolling Effect

### LINKED ISSUE #171: Chaotic Feat: Add Parallax Scrolling Effect
Parallax Scrolling Effect - I want to incorporate a Parallax Scrolling Effect into the design to create a sense of depth and motion as the user scrolls through the timeline. This effect will allow background elements to move at a slower pace than the foreground content, giving the illusion of layers and adding a more dynamic, immersive experience. The goal is to enhance the chaotic yet visually engaging atmosphere of the timeline, making it feel more interactive and modern while maintaining smooth and fluid transitions between different sections.

image

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

### PR DESCRIPTION
**Pull request by Riya7045**
Fixes #171

### CODE REVIEW

**Comment by vansh-codes** [comment]
Please share screenshot and videos

**Comment by Riya7045** [comment]
Screenshot 2024-10-29 002835
Screenshot 2024-10-29 002942
[screen-capture.webm](https://github.com/user-attachments/assets/2c7cbeae-6294-426e-b409-5120d2b46577)

**Comment by vansh-codes** [comment]
Where's the parallax effect in this? I didnt see it anywhere, can you pleasse explain??

**Comment by Riya7045** [comment]
In the video which i sent u ,the cubes which are moving from down to up and it is a different speed from the foreground is the parallax effect and also the colour bars on the topside is a part of it too.
Basically parallax effect or Parallax scrolling is a web site trend where the background content (i.e. an image) is moved at a different speed than the foreground content while scrolling.

**Review by vansh-codes — APPROVED** [review]

**Pull request merged**
