### PR TITLE
Improve  preloader

### PR DESCRIPTION
**Pull request by VidhanThakur09**
### Related Issue

Issue Fixed: #160 

### Description

Styling has been applied to the preloader. The preloader is present on all pages of the website with styling. 

*Improvements:*

1. *Optimized Preloader:* Enhanced the preloader animation on all pages to improve user experience.

2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.

3. *Dedicated Preloader  StyleSheet:* Created a separate CSS file named `" preloaderStyle.css"` to enhance the styling and functionality, ensuring better code organization and maintainability.

## How Has This Been Tested? 

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

## Screenshots 📷

**Before changes** 

Screenshot 2024-10-08 125957

**After adding preloader**

https://github.com/user-attachments/assets/44285cf7-94c8-4264-883e-0d4f2b21eba2

### CODE REVIEW

**Comment by VidhanThakur09** [comment]
@vansh-codes   could u please increase the level of this PR to level 3 , as I have to rearrange the PreLoader for all the  pages with styling? 
and please merge this before someone edit the codebase

**Comment by vansh-codes** [comment]
Resolve the conflicts

**Comment by VidhanThakur09** [comment]
@vansh-codes all the conflicts has been resolved

issue no - #160

**Comment by vansh-codes** [comment]
Hey @VidhanThakur09 
I just checked your work, you have just copy pasted the code from html file to react file and nothing else
It doesnt works like that
Also the preloader is not visible, there is some logic to make it visible when loading, and modifying the `index.html` is not at all a good practice
I cant merge this PR, you can either make the required changes and then let me know or else close this PR and issue as well

**Review by vansh-codes — CHANGES_REQUESTED** [review]
needs to be fixed as said or else the PR will be closed

**Comment by VidhanThakur09** [comment]
I will try to resolve the issue.

**Comment by vansh-codes** [comment]
Okay then resolve them and then let me know

**Pull request closed without merging**
