### PR TITLE
 Added vibrant color elements, border at the top and changed main heading's font style to make it more chaotic

### PR DESCRIPTION
**Pull request by MimanshaKaur**
**Changes successfully done!👍**

Here are the changes that i have made:

1.  I have designed and added a funny and bright border at the top of main page.
2.  I added some randomly floating bubbles and square shaped colorful objects in the background by making changes in the HTML & CSS code and by adding animations in it.
3.  By making it multi-colored and by changing the the font sizes of words in the heading... i have tried to give it a confusing/ chaotic yet readable look.
4.  Also, changed background color from simple black to dark gradient shades.

Previous Look:👇
Screenshot 2024-10-11 154034

After Changes New Look: 😍👇

[AwesomeScreenshot-10_14_2024,3_16_08AM.webm](https://github.com/user-attachments/assets/03ab8b8f-9a8b-48ae-8d52-446e8bcafc10)

@vansh-codes Thank you so much for this opportunity... hope you liked it👍

### CODE REVIEW

**Review by MimanshaKaur — COMMENTED** [review]
Done with Final Review

**Review by vansh-codes — APPROVED** [review]

**Comment by vansh-codes** [comment]
Hii @MimanshaKaur 
You told you will be working on React and making changes there but I see you have worked on html css only
Next time please do what you say!

**Comment by MimanshaKaur** [comment]
@vansh-codes actually sir you shared 2 deployment links  one for react and other for html css...and I have just made the changes in the one with react.

**Comment by vansh-codes** [comment]
You have made changes in html css, not react, no worries, let it be this time, next time be careful

**Comment by MimanshaKaur** [comment]
> You have made changes in html css, not react, no worries, let it be this time, next time be careful

Sure .. 👍

thank you.

**Pull request merged**
