### PR TITLE
Update ContactUs.html(Changed the UI of contact us page)

### PR DESCRIPTION
**Pull request by Bhumika-00**
Closes: #95

Added the transitions animations improve the colour thee and text style.

### CODE REVIEW

**Comment by vansh-codes** [comment]
Screenshot image is not available, also mention the issue on which you worked on the top of the PR description
`Closes: #issuenumber` like this

**Comment by Bhumika-00** [comment]
Okay

**Comment by Bhumika-00** [comment]
I have resolve the issue #95

**Comment by vansh-codes** [comment]
What about the screenshot you added in description? its not visible

**Comment by Bhumika-00** [comment]
let me upload the ss again

**Comment by Bhumika-00** [comment]
Screenshot from 2024-10-14 11-23-07
Screenshot from 2024-10-14 11-23-04
Screenshot from 2024-10-14 11-23-00
Also I have provided a video for better explanation of animation

**Comment by Bhumika-00** [comment]
Basically the background image is also moving

**Comment by Bhumika-00** [comment]
It is not getting updated here

**Pull request merged**
