### PR TITLE
Update timeline page and fix animation #34

### PR DESCRIPTION
**Pull request by Mr-DK07**
Hey @vansh-codes I have updated timeline page. Just take a look and let me know is there anything you want to improve.
Here is the video of the changes.

https://github.com/user-attachments/assets/75a9e816-787c-49f1-9e92-82057f351d1f

If you like it, please increase level1 to at least level2 or level3. 
Thanks!

### CODE REVIEW

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Do the appropriate changes

**Comment by Mr-DK07** [comment]
@vansh-codes  check it now.

**Comment by vansh-codes** [comment]
Share the updated code video

**Comment by Mr-DK07** [comment]
Uploading Recording 2024-10-08 161131.mp4…

**Pull request merged**
